### ISSUE TITLE
Would you please tell me how the scores are measured?

### ISSUE THREAD

**Issue by ukjung21** [Lion-ZS/GIE#2]
In paper, the score is measured based on distance(in code, 'hyp_distance' method)

![화면 캡처 2023-01-26 230930](https://user-images.githubusercontent.com/80200554/214856936-e4d489e4-7fda-4d76-b325-216480a517c0.png)

However, in the code, score is something different with what I thought. That is, there's no use of distance function

`(att_q * rel[0] - translation1) @ entity1.t() +(att_q * rel[1] + translation2) @ entity2.t()`

Am I wrong? Then, would you please tell me why?

**Comment by Lion-ZS** [comment]
Thank you for your attention. The  terms  translation1 and translation2 represent translation transformation in Eq.(6) in the paper. To simplify the expression, we set b to 0 in Eq.(10). In this way, we set the distance of $d_c$ as the inner product distance and hence we derive the Eq.(10).




At 2023-01-26 22:13:41, "ukjung21" ***@***.***> wrote:

In paper, the score is measured based on distance(in code, 'hyp_distance' method)

However, in the code, score is something different with what I thought, that there's no use of distance function

(att_q * rel[0] - translation1) @ entity1.t() +(att_q * rel[1] + translation2) @ entity2.t()

Am I wrong? Then, would you please tell me why?

**Comment by ukjung21** [comment]
> Thank you for your attention. The terms translation1 and translation2 represent translation transformation in Eq.(6) in the paper. To simplify the expression, we set b to 0 in Eq.(10). In this way, we set the distance of $d_c$ as the inner product distance and hence we derive the Eq.(10). At 2023-01-26 22:13:41, "ukjung21" ***@***.***> wrote: In paper, the score is measured based on distance(in code, 'hyp_distance' method) However, in the code, score is something different with what I thought, that there's no use of distance function (att_q * rel[0] - translation1) @ entity1.t() +(att_q * rel[1] + translation2) @ entity2.t() Am I wrong? Then, would you please tell me why? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you for your explanation. I had thought that $d_c$ in Eq.(10) is the same one of Eq.(3). Now I understand it, thank you!

**Comment by ukjung21** [comment]
I have another question.
I wonder why the score function consider the relations of both direction, that is, (h,r,t) and (t. r', h), wher r' is inverse of r.
![image](https://user-images.githubusercontent.com/80200554/219292256-4af93257-6346-43f6-8c7c-9e3204c24286.png)

Is it for learning representation of the inverse relation as well as the original relation?
Or is there any other reason for?
